### PR TITLE
Fix #40

### LINKED ISSUE #40: Unresolved Week 7 tasks
* `README.md` CI banners not pointing to own project
* csiongn's picture not named after his Github username as required
* Not all AB3 references removed from UG

### PR DESCRIPTION
**Pull request by ong-yinggao98**
* Rename choonsiong.png to csiongn.png
* Moved CI status reference to tp
* Rename all AddressBook references in UG to Reeve

### CODE REVIEW

**Review by csiongn — APPROVED** [review]
thank you, LGTM

**Review by VaishakAnand — APPROVED** [review]
LGTM, thank you!

**Review by hogantan — APPROVED** [review]
LGTM

**Review by AlexCQY — APPROVED** [review]
LGTM

**Pull request merged**
