### PR TITLE
Update save to json

### LINKED ISSUE #69: Update save-to-JSON functionality
Right now JsonAdaptedStudent does not save our admin classes, it has to be updated. In particular we need to change the admin details back into the original string they were as they were parsed into the constructor.

Reeve saves data by taking all the `Student` objects in Reeve and mapping them to `JsonAdaptedStudent` objects so they can be saved as a String. A JsonAdaptedStudent basically has all the data saved the form of a String when it is first parsed into the constructor (e.g. a `ClassTime` of Monday, 12pm-3pm will have to be saved as "1 1200-1500").

Upon starting up Reeve the application will then turn read "1 1200-1500" and then call `ClassTime::new` on it to produce the ClassTime object.

### PR DESCRIPTION
**Pull request by AlexCQY**
-add JsonAdaptedAdmin for interchanging between json and admin object
-add tests for JsonAdaptedAdmin
-update json files (tests)

### CODE REVIEW

**Review by ong-yinggao98 — APPROVED** [review]
LTGM

**Review by hogantan — APPROVED** [review]
LGTM. Note that there are conflicts to be resolved due to merge with add command.

**Review by VaishakAnand — APPROVED** [review]
LGTM

**Review by csiongn — APPROVED** [review]
LGTM

**Pull request merged**
