### PR TITLE
Add ParserUtil tests and squash bugs

### PR DESCRIPTION
**Pull request by ong-yinggao98**
Fixed:
* parseYear() not parsing trimmed year
* parseSchool() not parsing trimmed school

### CODE REVIEW

**Review by hogantan — APPROVED** [review]
LGTM. Very comprehensive test cases! Nice!

**Review by AlexCQY — APPROVED** [review]
Nice

**Review by VaishakAnand — APPROVED** [review]
Legend, thank you!

**Review by csiongn — APPROVED** [review]
Thanks for this!

**Pull request merged**
