### PR TITLE
Add Payment and Fee fields; Resolve #46

### LINKED ISSUE #46: Implement fees and payment date data

### PR DESCRIPTION
**Pull request by ong-yinggao98**
TODO: Implementation

### CODE REVIEW

**Comment by ong-yinggao98** [comment]
Nabei I test all the methods this bot still say less coverage

**Review by hogantan — APPROVED** [review]
LGTM

**Review by AlexCQY — APPROVED** [review]
LGTM

**Review by csiongn — APPROVED** [review]
LGTM

**Review by VaishakAnand — APPROVED** [review]
LGTM

**Pull request merged**
