### PR TITLE
Update DG

### PR DESCRIPTION
**Pull request by hogantan**
Add (Diagrams):
* ExamCommandClassDiagram
ExamCommandClassDiagram

* ExamStatsActivityDiagram
ExamStatsActivityDiagram

* ExamStatsSequenceDiagram
ExamStatsSequenceDiagram

* ToggleStudentCardSequenceDiagram
ToggleStudentCardSequenceDiagram

Add (DG details):
* Help command details
* Toggle command details
* Delete command details
* Add Exam command details
* Delete Exam command details
* Exam Stats command details
* User Stories
* Use Cases

Add (Misc):
* exam_stats_icon

Update:
UG structure
DG structure and details

### CODE REVIEW

**Review by ong-yinggao98 — CHANGES_REQUESTED** [review]
The activity diagrams might be too complex, perhaps we should split some up using the rake symbol. It seems that this guy here made a rake symbol that you can define in `style.puml`
https://forum.plantuml.net/195/is-there-any-support-for-subactivity-or-the-rake-symbol
After you do so I will have to do it too :(

Also, you could number your figures after the section
(e.g the third diagram in section 7.8.2 could be named fig 7.8.2.3)

**Comment by hogantan** [comment]
> The activity diagrams might be too complex, perhaps we should split some up using the rake symbol. It seems that this guy here made a rake symbol that you can define in `style.puml`

Do you mean the sequence diagrams or the activity diagrams?

**Comment by ong-yinggao98** [comment]
> 
> 
> > The activity diagrams might be too complex, perhaps we should split some up using the rake symbol. It seems that this guy here made a rake symbol that you can define in `style.puml`
> 
> Do you mean the sequence diagrams or the activity diagrams?

Oh now that I look at it it's not your activity diagrams but @VaishakAnand and mine >:(
Nvm

**Review by AlexCQY — APPROVED** [review]
lgtm

**Comment by ong-yinggao98** [comment]
Could you number your figures before I merge?

**Comment by hogantan** [comment]
> Could you number your figures before I merge?

Do you think the numbering convention of following the table contents could get quite messy? (e.g. Figure 6.8.1.1a ) 

Should we follow the traditional style instead? (Figure 1, Figure 2, etc.)

**Comment by ong-yinggao98** [comment]
> Should we follow the traditional style instead? (Figure 1, Figure 2, etc.)

Hmmm I guess aight

**Review by ong-yinggao98 — APPROVED** [review]

**Pull request merged**
