### PR TITLE
Add rake symbol, improve activity diagrams

### PR DESCRIPTION
**Pull request by ong-yinggao98**
* Remove low-level details for QuestionCommands
* Split activity diagrams up for readability

If you want to use the rake symbol for your own activity diagrams, just add `!include style.puml` under `@startuml` and reference it with `:Do something <$rake>;`

### CODE REVIEW

**Review by VaishakAnand — COMMENTED** [review]
For all the sequence diagrams, does the newly created Student really get destroyed, since this Student object replaces the older student in the Model, when `setStudent(student, copy)` is called. 

I can't comment on the exact lines since they're from a previous pr. Outside of this, everything looks ok to me.

**Comment by ong-yinggao98** [comment]
> 
> 
> For all the sequence diagrams, does the newly created Student really get destroyed, since this Student object replaces the older student in the Model, when `setStudent(student, copy)` is called.
> 
> I can't comment on the exact lines since they're from a previous pr. Outside of this, everything looks ok to me.

The command takes an existing student (the student in the diagram) and creates a copy from it, then replaces it in the model. Then the old student should get deleted since nothing points to it anymore.

**Comment by VaishakAnand** [comment]
> > For all the sequence diagrams, does the newly created Student really get destroyed, since this Student object replaces the older student in the Model, when `setStudent(student, copy)` is called.
> > I can't comment on the exact lines since they're from a previous pr. Outside of this, everything looks ok to me.
> 
> The command takes an existing student (the student in the diagram) and creates a copy from it, then replaces it in the model. Then the old student should get deleted since nothing points to it anymore.

AH ok gotcha. Then in that case, should we show the new student object (copy) creation? Or would that be considered a low level detail that we don't have to show.

**Comment by ong-yinggao98** [comment]
> 
> 
> > > For all the sequence diagrams, does the newly created Student really get destroyed, since this Student object replaces the older student in the Model, when `setStudent(student, copy)` is called.
> > > I can't comment on the exact lines since they're from a previous pr. Outside of this, everything looks ok to me.
> > 
> > 
> > The command takes an existing student (the student in the diagram) and creates a copy from it, then replaces it in the model. Then the old student should get deleted since nothing points to it anymore.
> 
> AH ok gotcha. Then in that case, should we show the new student object (copy) creation? Or would that be considered a low level detail that we don't have to show.

I feel like I can elaborate on it in the description bah

**Comment by VaishakAnand** [comment]
> > > > For all the sequence diagrams, does the newly created Student really get destroyed, since this Student object replaces the older student in the Model, when `setStudent(student, copy)` is called.
> > > > I can't comment on the exact lines since they're from a previous pr. Outside of this, everything looks ok to me.
> > > 
> > > 
> > > The command takes an existing student (the student in the diagram) and creates a copy from it, then replaces it in the model. Then the old student should get deleted since nothing points to it anymore.
> > 
> > 
> > AH ok gotcha. Then in that case, should we show the new student object (copy) creation? Or would that be considered a low level detail that we don't have to show.
> 
> I feel like I can elaborate on it in the description bah

hmm okay, i think I'll show the creation in my diagrams tho, if thats fine. LGTM

**Review by VaishakAnand — APPROVED** [review]

**Pull request merged**
