### PR TITLE
Update GUI (Resolves #16)

### LINKED ISSUE #8: As an expert user, I can view my student's details
... so that I can refer to them when needed. 

- Contact information
- Class Address
- School / Year
- Class time
- Payment status
- Questions
- Additional Details

### LINKED ISSUE #16: Update GUI to support displaying Student details

### PR DESCRIPTION
**Pull request by hogantan**
Update GUI to display all fields 
Reorganize GUI layout
Refer to the Telegram chat for screenshots of GUI

### CODE REVIEW

**Review by ong-yinggao98 — APPROVED** [review]
Nice work!

**Review by VaishakAnand — APPROVED** [review]
LGTM, thank you!

**Review by AlexCQY — APPROVED** [review]
Nice. Thanks.

**Review by csiongn — APPROVED** [review]
Thanks!

**Pull request merged**
